// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD70pPWvH3A_wUqs7eJun8-75vc5z33fUM',
    appId: '1:239923189175:web:2e3c71c4d6f37ec34dc432',
    messagingSenderId: '239923189175',
    projectId: 'flutter-firebase-project-10cf6',
    authDomain: 'flutter-firebase-project-10cf6.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-10cf6.appspot.com',
    measurementId: 'G-QB62M6KV3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZBL_rYDjJNbDTy9ywgWxt0rrR6I5nHHw',
    appId: '1:239923189175:android:41f92192e40c5a294dc432',
    messagingSenderId: '239923189175',
    projectId: 'flutter-firebase-project-10cf6',
    storageBucket: 'flutter-firebase-project-10cf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPl0HnJBArOiSwmyKi4tzxyidtThIa974',
    appId: '1:239923189175:ios:fb52c503b2989fbd4dc432',
    messagingSenderId: '239923189175',
    projectId: 'flutter-firebase-project-10cf6',
    storageBucket: 'flutter-firebase-project-10cf6.appspot.com',
    iosClientId: '239923189175-3m0sa55h9bsorgnqs95289trvv0almei.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPl0HnJBArOiSwmyKi4tzxyidtThIa974',
    appId: '1:239923189175:ios:fb52c503b2989fbd4dc432',
    messagingSenderId: '239923189175',
    projectId: 'flutter-firebase-project-10cf6',
    storageBucket: 'flutter-firebase-project-10cf6.appspot.com',
    iosClientId: '239923189175-3m0sa55h9bsorgnqs95289trvv0almei.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );
}
